### ISSUE TITLE
Arguments: Crash on arguments

### ISSUE THREAD

**Issue by terkelg** [Khala-wan/Slarder#3]
If you pass arguments using `.arguments` the program crashes. Is there another way to pass arguments to the script?

![screen shot 2017-09-18 at 11 01 25 am](https://user-images.githubusercontent.com/2302254/30556742-c2a05bd8-9c60-11e7-9926-dc2a31ea4c56.png)

**Comment by Khala-wan** [comment]
Sorry to see your feedback now, can you provide the context of the code as you passed the arguments? To help me locate the problem as soon as possible.
